[package]
name = "domain"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.87"
sea-orm = "1.0.1"
serde = { version = "1.0.210", features = ["derive"] }
tokio = { version = "1.28.0", features = ["full"] }
migration = { path = "../migration" }
